# render.yaml
services:
  - type: web
    name: nuam-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn PrNuam3.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nuam-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
    healthCheckPath: /health/
    autoDeploy: true

databases:
  - name: nuam-db
    databaseName: nuam
    user: nuam_user
    plan: free